# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20160426_2018'),
        ('identificacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='identify',
            name='usersys',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usersys'),
        ),
    ]
