# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identificacion', '0002_identify_usersys'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('identify', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='identificacion.Identify')),
            ],
        ),
    ]
