# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identificacion', '0003_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identify',
            name='usersys',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usersys'),
        ),
    ]
