# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identificacion', '0005_auto_20160428_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='idtype',
            new_name='identify',
        ),
    ]
