# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logged',
        ),
    ]
