# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_logged'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piepeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipe', models.CharField(max_length=500)),
            ],
        ),
    ]
