# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_piepeline'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Piepeline',
            new_name='Pipeline',
        ),
    ]
