# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20160504_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='pipe',
            field=models.CharField(max_length=5000),
        ),
    ]
