# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagenes', '0003_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imagenes.Server'),
        ),
    ]
