# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_auto_20160430_2346'),
        ('imagenes', '0004_auto_20160430_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagenes.Image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usersys')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='users',
            field=models.ManyToManyField(through='imagenes.UserImage', to='usuarios.Usersys'),
        ),
    ]
