# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagenes', '0009_auto_20160501_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imagenes.Server'),
        ),
        migrations.AlterField(
            model_name='image',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, through='imagenes.UserImage', to='usuarios.Usersys'),
        ),
    ]
