# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('server', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musica.Song'),
        ),
    ]
