# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0003_remove_artist_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='image',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
