# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 01:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_merge'),
        ('musica', '0004_auto_20160426_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='song',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multimedia.Server'),
        ),
        migrations.AddField(
            model_name='usersong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musica.Song'),
        ),
        migrations.AddField(
            model_name='usersong',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usersys'),
        ),
        migrations.AddField(
            model_name='song',
            name='users',
            field=models.ManyToManyField(blank=True, through='musica.UserSong', to='usuarios.Usersys'),
        ),
    ]
