# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0005_auto_20160502_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.CharField(default='BLANK', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='artista',
            field=models.CharField(default='BLANK', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='imagen',
            field=models.CharField(default='BLANK', max_length=255),
            preserve_default=False,
        ),
    ]
