# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 23:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0006_auto_20160503_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artista',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='imagen',
            new_name='image',
        ),
    ]
