# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20160426_0206'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='D',
            new_name='User',
        ),
    ]
