# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0001_initial'),
        ('usuarios', '0003_auto_20160426_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='songs',
            field=models.ManyToManyField(to='musica.Song'),
        ),
    ]
