# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20160426_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usersys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_names', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(verbose_name='Fecha de alta')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='identification',
        ),
        migrations.RemoveField(
            model_name='user',
            name='songs',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
