# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 02:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20160426_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersys',
            name='date_added',
            field=models.DateField(default=datetime.date(2016, 4, 27), verbose_name='Fecha de alta'),
        ),
    ]
