# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_auto_20160428_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersys',
            name='date_added',
            field=models.DateField(auto_now=True, verbose_name='Fecha de alta'),
        ),
    ]
