# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 01:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_auto_20160428_1910'),
        ('usuarios', '0014_auto_20160501_0006'),
    ]

    operations = [
    ]
